video:
  width:      1024
  height:     768
  depth:      32
  drawMode:   VRAMBuffers
  fullscreen: false
frameProfiler:
  enabled:   false
  frameSkip: 0
  memoryMiB: 64
sound:
  menuMusic: music/menu/ville_seppanen-1_g.ogg
  musicVolume: 0.08
  soundVolume: 0.24
