/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/
module derelict.allegro.ttf;

private
{
    import derelict.allegro.allegrotypes;
    import derelict.allegro.font;

    import derelict.util.compat;
    import derelict.util.loader;
}

enum
{
    ALLEGRO_TTF_NO_KERNING = 1,
    ALLEGRO_TTF_MONOCHROME = 2,
}

extern(C)
{
    alias ALLEGRO_FONT* function(in char*,int, int) da_al_load_ttf_font;
    alias ALLEGRO_FONT* function(ALLEGRO_FILE*,in char*,int,int) da_al_load_ttf_font_f;
    alias bool function() da_al_init_ttf_addon;
    alias void function() da_al_shutdown_ttf_addon;
    alias uint function() da_al_get_allegro_ttf_version;
}

mixin(gsharedString!() ~
"
da_al_load_ttf_font al_load_ttf_font;
da_al_load_ttf_font_f al_load_ttf_font_f;
da_al_init_ttf_addon al_init_ttf_addon;
da_al_shutdown_ttf_addon al_shutdown_ttf_addon;
da_al_get_allegro_ttf_version al_get_allegro_ttf_version;
");

class DerelictAllegroTTFLoader : SharedLibLoader
{
public:
    this()
    {
        super(
        // Windows
        "allegro_ttf-5.0.5-mt.dll,allegro_ttf-5.0.4-mt.dll,allegro_ttf-5.0.3-mt.dll,"
        "allegro_ttf-5.0.2-mt.dll,allegro_ttf-5.0.1-mt.dll,allegro_ttf-5.0.0-mt.dll",
        // Linux
        "liballegro_ttf-5.0.5.so,liballegro_ttf-5.0.so",
        // OSX
        "../Frameworks/Allegrottf-5.0.framework,/Library/Frameworks/AllegroTTF-5.0.framwork,"
        "liballegro_ttf-5.0.5.dylib,liballegro_ttf-5.0.dylib"
        );
    }

protected:
    override void loadSymbols()
    {
        bindFunc(cast(void**)&al_load_ttf_font, "al_load_ttf_font");
        bindFunc(cast(void**)&al_load_ttf_font_f, "al_load_ttf_font_f");
        bindFunc(cast(void**)&al_init_ttf_addon, "al_init_ttf_addon");
        bindFunc(cast(void**)&al_shutdown_ttf_addon, "al_shutdown_ttf_addon");
        bindFunc(cast(void**)&al_get_allegro_ttf_version, "al_get_allegro_ttf_version");
    }
}

DerelictAllegroTTFLoader DerelictAllegroTTF;

static this()
{
    DerelictAllegroTTF = new DerelictAllegroTTFLoader();
}

static ~this()
{
    if(SharedLibLoader.isAutoUnloadEnabled())
        DerelictAllegroTTF.unload();
}