/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/
module derelict.ogg.oggfuncs;

private
{
    import derelict.util.compat;
    import derelict.ogg.oggtypes;
}

extern(C)
{
    mixin(gsharedString!() ~
    "
    void function(oggpack_buffer *b) oggpack_writeinit;
    void function(oggpack_buffer *b, int  bits) oggpack_writetrunc;
    void function(oggpack_buffer *b) oggpack_writealign;
    void function(oggpack_buffer *b, void *source, int bits) oggpack_writecopy;
    void function(oggpack_buffer *b) oggpack_reset;
    void function(oggpack_buffer *b) oggpack_writeclear;
    void function(oggpack_buffer *b, ubyte *buf, int bytes) oggpack_readinit;
    void function(oggpack_buffer *b, uint value, int bits) oggpack_write;
    int  function(oggpack_buffer *b, int bits) oggpack_look;
    int  function(oggpack_buffer *b) oggpack_look1;
    void function(oggpack_buffer *b, int bits) oggpack_adv;
    void function(oggpack_buffer *b) oggpack_adv1;
    int  function(oggpack_buffer *b, int bits) oggpack_read;
    int  function(oggpack_buffer *b) oggpack_read1;
    int  function(oggpack_buffer *b) oggpack_bytes;
    int  function(oggpack_buffer *b) oggpack_bits;
    ubyte *function(oggpack_buffer *b) oggpack_get_buffer;

    void function(oggpack_buffer *b) oggpackB_writeinit;
    void function(oggpack_buffer *b, int  bits) oggpackB_writetrunc;
    void function(oggpack_buffer *b) oggpackB_writealign;
    void function(oggpack_buffer *b, void *source, int bits) oggpackB_writecopy;
    void function(oggpack_buffer *b) oggpackB_reset;
    void function(oggpack_buffer *b) oggpackB_writeclear;
    void function(oggpack_buffer *b, ubyte *buf, int bytes) oggpackB_readinit;
    void function(oggpack_buffer *b, uint value, int bits) oggpackB_write;
    int  function(oggpack_buffer *b, int bits) oggpackB_look;
    int  function(oggpack_buffer *b) oggpackB_look1;
    void function(oggpack_buffer *b, int bits) oggpackB_adv;
    void function(oggpack_buffer *b) oggpackB_adv1;
    int  function(oggpack_buffer *b, int bits) oggpackB_read;
    int  function(oggpack_buffer *b) oggpackB_read1;
    int  function(oggpack_buffer *b) oggpackB_bytes;
    int  function(oggpack_buffer *b) oggpackB_bits;
    ubyte *function(oggpack_buffer *b) oggpackB_get_buffer;

    int     function(ogg_stream_state *os, ogg_packet *op) ogg_stream_packetin;
    int     function(ogg_stream_state *os, ogg_page *og) ogg_stream_pageout;
    int     function(ogg_stream_state *os, ogg_page *og) ogg_stream_flush;

    int     function(ogg_sync_state *oy) ogg_sync_init;
    int     function(ogg_sync_state *oy) ogg_sync_clear;
    int     function(ogg_sync_state *oy) ogg_sync_reset;
    int     function(ogg_sync_state *oy) ogg_sync_destroy;
    byte*   function(ogg_sync_state *oy, int size) ogg_sync_buffer;
    int     function(ogg_sync_state *oy, int bytes) ogg_sync_wrote;
    int     function(ogg_sync_state *oy,ogg_page *og) ogg_sync_pageseek;
    int     function(ogg_sync_state *oy, ogg_page *og) ogg_sync_pageout;
    int     function(ogg_stream_state *os, ogg_page *og) ogg_stream_pagein;
    int     function(ogg_stream_state *os,ogg_packet *op) ogg_stream_packetout;
    int     function(ogg_stream_state *os,ogg_packet *op) ogg_stream_packetpeek;

    int     function(ogg_stream_state *os,int serialno) ogg_stream_init;
    int     function(ogg_stream_state *os) ogg_stream_clear;
    int     function(ogg_stream_state *os) ogg_stream_reset;
    int     function(ogg_stream_state *os,int serialno) ogg_stream_reset_serialno;
    int     function(ogg_stream_state *os) ogg_stream_destroy;
    int     function(ogg_stream_state *os) ogg_stream_eos;
    void    function(ogg_page *og) ogg_page_checksum_set;
    int     function(ogg_page *og) ogg_page_version;
    int     function(ogg_page *og) ogg_page_continued;
    int     function(ogg_page *og) ogg_page_bos;
    int     function(ogg_page *og) ogg_page_eos;
    ogg_int64_t function(ogg_page *og) ogg_page_granulepos;
    int     function(ogg_page *og) ogg_page_serialno;
    int     function(ogg_page *og) ogg_page_pageno;
    int     function(ogg_page *og) ogg_page_packets;
    void    function(ogg_packet *op) ogg_packet_clear;
    ");
}