/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/
module derelict.sfml.sfuncs;

private
{
    import derelict.util.compat;
    import derelict.sfml.stypes;
}

extern(C)
{
    alias sfClock* function() da_sfClock_Create;
    alias void function(sfClock*) da_sfClock_Destroy;
    alias float function(sfClock*) da_sfClock_GetTime;
    alias void function(sfClock*) da_sfClock_Reset;
    alias sfMutex* function() da_sfMutex_Create;
    alias void function(sfMutex*) da_sfMutex_Destroy;
    alias void function(sfMutex*) da_sfMutex_Lock;
    alias void function(sfMutex*) da_sfMutex_Unlock;
    alias void function(uint) da_sfRandom_SetSeed;
    alias uint function() da_sfRandom_GetSeed;
    alias float function(float, float) da_sfRandom_Float;
    alias int function(int, int) da_sfRandom_Int;
    alias void function(float) da_sfSleep;
    alias sfThread* function(void function(void*), void*) da_sfThread_Create;
    alias void function(sfThread*) da_sfThread_Destroy;
    alias void function(sfThread*) da_sfThread_Launch;
    alias void function(sfThread*) da_sfThread_Wait;
    alias void function(sfThread*) da_sfThread_Terminate;
}

mixin(gsharedString!() ~
"
da_sfClock_Create sfClock_Create;
da_sfClock_Destroy sfClock_Destroy;
da_sfClock_GetTime sfClock_GetTime;
da_sfClock_Reset sfClock_Reset;
da_sfMutex_Create sfMutex_Create;
da_sfMutex_Destroy sfMutex_Destroy;
da_sfMutex_Lock sfMutex_Lock;
da_sfMutex_Unlock sfMutex_Unlock;
da_sfRandom_SetSeed sfRandom_SetSeed;
da_sfRandom_GetSeed sfRandom_GetSeed;
da_sfRandom_Float sfRandom_Float;
da_sfRandom_Int sfRandom_Int;
da_sfSleep sfSleep;
da_sfThread_Create sfThread_Create;
da_sfThread_Destroy sfThread_Destroy;
da_sfThread_Launch sfThread_Launch;
da_sfThread_Wait sfThread_Wait;
da_sfThread_Terminate sfThread_Terminate;
");